### ISSUE TITLE
Change YAML into JSON

### ISSUE THREAD

**Issue by skysomorphic** [yagarea/confgit#27]
Not really very important, just gets rid of `PyYAML` as a dependency by using the built-in `json` module instead

**Comment by yagarea** [comment]
I am not sure about this change. I like `yaml`, because it is much easier to edit and read manually.

I know it is a bit bloated, but being able comfortably manage config manually is important thing in my opinion.

**Comment by skysomorphic** [comment]
Good point, I'll shelve this idea for now
